"""
Office & Document Automation Builder for macOS
Generates presentations (.pptx), spreadsheets (.xlsx), documents (.docx), and PDFs.
"""

import os
import subprocess
from pathlib import Path
from typing import Dict, Any, List

def get_desktop_dir() -> Path:
    return Path(os.path.expanduser("~/Desktop"))

def create_presentation(topic: str, slides_data: List[Dict[str, Any]] = None, filename: str = "") -> Dict[str, Any]:
    """Generates a PowerPoint presentation on the user's desktop."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        return {"status": "error", "message": "python-pptx library not installed."}

    if not filename:
        clean_topic = "".join(c for c in topic if c.isalnum() or c in " _-").strip()[:30]
        filename = f"{clean_topic or 'Presentation'}.pptx"

    out_path = get_desktop_dir() / filename
    
    prs = Presentation()
    # 16:9 widescreen layout
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = topic.title()
    subtitle.text = "Generated by SUPERNOVA macOS Assistant"

    # Default slide structure if none provided
    if not slides_data:
        slides_data = [
            {"title": "Executive Summary", "points": ["Key background and objectives", "Current market landscape", "Strategic opportunities"]},
            {"title": "Key Insights & Architecture", "points": ["High-performance execution", "Integrated automation and vision", "Seamless user workflow"]},
            {"title": "Next Steps & Roadmap", "points": ["Phase 1: Implementation", "Phase 2: Validation & Testing", "Phase 3: Deployment"]}
        ]

    for item in slides_data:
        bullet_layout = prs.slide_layouts[1]
        s = prs.slides.add_slide(bullet_layout)
        s.shapes.title.text = item.get("title", "Overview")
        tf = s.placeholders[1].text_frame
        points = item.get("points", [])
        if points:
            tf.text = points[0]
            for pt in points[1:]:
                p = tf.add_paragraph()
                p.text = pt
                p.level = 0

    prs.save(str(out_path))
    
    # Open presentation on Mac
    try:
        subprocess.run(["open", str(out_path)], capture_output=True)
    except Exception:
        pass

    return {
        "status": "success",
        "message": f"Successfully created and opened presentation: {out_path.name}",
        "file_path": str(out_path)
    }

def create_spreadsheet(title: str, headers: List[str] = None, rows: List[List[Any]] = None, filename: str = "") -> Dict[str, Any]:
    """Generates an Excel workbook on the user's desktop."""
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    except ImportError:
        return {"status": "error", "message": "openpyxl library not installed."}

    if not filename:
        clean_title = "".join(c for c in title if c.isalnum() or c in " _-").strip()[:30]
        filename = f"{clean_title or 'Spreadsheet'}.xlsx"

    out_path = get_desktop_dir() / filename
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = (title[:25] or "Sheet1")

    # Header styling
    if not headers:
        headers = ["Item #", "Description", "Category", "Quantity", "Unit Price", "Total"]
    
    if not rows:
        rows = [
            [1, "Product Alpha", "Hardware", 10, 150.00, "=D2*E2"],
            [2, "Service Subscription", "Software", 5, 29.99, "=D3*E3"],
            [3, "Enterprise Support", "Services", 1, 500.00, "=D4*E4"]
        ]

    # Write Headers
    header_fill = PatternFill(start_color="1A202C", end_color="1A202C", fill_type="solid")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFAA30")
    
    for col_idx, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=h)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # Write Rows
    for row_idx, row_data in enumerate(rows, 2):
        for col_idx, val in enumerate(row_data, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.font = Font(name="Calibri", size=10)

    # Auto-adjust column widths
    for col in ws.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = openpyxl.utils.get_column_letter(col[0].column)
        ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

    wb.save(str(out_path))

    try:
        subprocess.run(["open", str(out_path)], capture_output=True)
    except Exception:
        pass

    return {
        "status": "success",
        "message": f"Successfully created and opened spreadsheet: {out_path.name}",
        "file_path": str(out_path)
    }

def create_document(title: str, content: str = "", filename: str = "") -> Dict[str, Any]:
    """Generates a Word (.docx) document on the user's desktop."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
    except ImportError:
        return {"status": "error", "message": "python-docx library not installed."}

    if not filename:
        clean_title = "".join(c for c in title if c.isalnum() or c in " _-").strip()[:30]
        filename = f"{clean_title or 'Document'}.docx"

    out_path = get_desktop_dir() / filename
    doc = Document()
    
    doc.add_heading(title, 0)
    doc.add_paragraph("Generated by SUPERNOVA macOS Assistant\n")
    
    if content:
        for para in content.split("\n\n"):
            if para.strip():
                doc.add_paragraph(para.strip())
    else:
        doc.add_paragraph("Executive brief and notes prepared automatically.")

    doc.save(str(out_path))
    
    try:
        subprocess.run(["open", str(out_path)], capture_output=True)
    except Exception:
        pass

    return {
        "status": "success",
        "message": f"Successfully created and opened document: {out_path.name}",
        "file_path": str(out_path)
    }
